CHANGELOG.md, settings/TagSettings.js, settings/index.js, translations/ui-tags/en.json
https://issues.folio.org/browse/FOLIO-1302
=> Add ability to enable tags app. Fixes FOLIO-1302

package.json
https://issues.folio.org/browse/STRIPES-557
=> Remove stripes-core from devDependencies. Part of STRIPES-557

settings/index.js
https://issues.folio.org/browse/STCOM-330
=> STCOM-330 Get Settings from stripes-smart-components

CHANGELOG.md, package.json, settings/TagSettings.js, settings/index.js
Uses new `@folio/stripes` package.
=> Use stripes 1.0

translations/ui-tags/ca.json, translations/ui-tags/fr_FR.json, translations/ui-tags/hu.json
=> Update translation strings as of 20181004T193841

settings/TagSettings.js
https://issues.folio.org/browse/UITAG-8
=> Enable tags by default. Fixes UITAG-8.

translations/ui-tags/ar.json
=> Update translation strings as of 20181031T224505

translations/ui-tags/ar.json
=> Update translation strings as of 20181112T151205

translations/ui-tags/pt_PT.json
=> Update translation strings as of 20181212T135930

translations/ui-tags/zh_CN.json
=> Update translation strings as of 20190108T192353

translations/ui-tags/en_SE.json
=> Update translation strings as of 20190110T173959

translations/ui-tags/pt_PT.json
=> Update translation strings as of 20190211T033248

translations/ui-tags/it_IT.json
=> Update translation strings as of 20190312T123958

translations/ui-tags/es_419.json
=> Update translation strings as of 20190422T163602

translations/ui-tags/it_IT.json
=> Update translation strings as of 20190919T124724

translations/ui-tags/ru.json, translations/ui-tags/zh_TW.json
=> Update translation strings as of 20191014T135140

translations/ui-tags/ja.json
=> Update translation strings as of 20191028T205642

translations/ui-tags/he.json
=> Update translation strings as of 20191113T214202

translations/ui-tags/it_IT.json
=> Update translation strings as of 20191119T231120

translations/ui-tags/fr_FR.json
=> Update translation strings as of 20191122T140350

translations/ui-tags/fr_FR.json
=> Update translation strings as of 20191125T160504

translations/ui-tags/ur.json
=> Update translation strings as of 20200210T220102

translations/ui-tags/ja.json
=> Update translation strings as of 20200413T183215

translations/ui-tags/ja.json
=> Update translation strings as of 20200420T134821

translations/ui-tags/zh_TW.json
=> Update translation strings as of 20200424T193712

translations/ui-tags/zh_TW.json
=> Update translation strings as of 20200428T150732

translations/ui-tags/zh_TW.json
=> Update translation strings as of 20200505T210535

translations/ui-tags/ar.json, translations/ui-tags/ca.json, translations/ui-tags/da.json, translations/ui-tags/de.json, translations/ui-tags/en_GB.json, translations/ui-tags/en_SE.json, translations/ui-tags/en_US.json, translations/ui-tags/es.json, translations/ui-tags/es_419.json, translations/ui-tags/es_ES.json, translations/ui-tags/fr.json, translations/ui-tags/fr_FR.json, translations/ui-tags/he.json, translations/ui-tags/hu.json, translations/ui-tags/it_IT.json, translations/ui-tags/ja.json, translations/ui-tags/pt_BR.json, translations/ui-tags/pt_PT.json, translations/ui-tags/ru.json, translations/ui-tags/ur.json, translations/ui-tags/zh_CN.json, translations/ui-tags/zh_TW.json
=> Update translation strings as of 20200716T140311

translations/ui-tags/zh_CN.json
=> Update translation strings as of 20200721T202356

translations/ui-tags/pl.json
=> Update translation strings as of 20200924T211627

translations/ui-tags/it_IT.json
=> Update translation strings as of 20201105T151643

translations/ui-tags/ber.json
=> Update translation strings as of 20201109T135508

translations/ui-tags/de.json
=> Update translation strings as of 20201119T214636

CHANGELOG.md, package.json, translations/ui-tags/en.json
Update permission name for Tags settings
https://issues.folio.org/browse/UITAG-40
=> UITAG-40 Update permission name for Tags settings

CHANGELOG.md, package.json
Increment `react-redux`, `redux-form`, and `@folio/stripes`.
Refs [UITAG-42](https://issues.folio.org/browse/UITAG-42), [STRIPES-721](https://issues.folio.org/browse/STRIPES-721)
=> UITAG-42 increment stripes, react-redux

package.json
https://issues.folio.org/browse/UITAG-43
=> UITAG-43 Update stripes-cli to v2

CHANGELOG.md, package.json
https://issues.folio.org/browse/UITAG-47
Increment stripes to v7, react to v17.
=> UITAG-47: Increment stripes to v7, react to v17

.github/workflows/build-npm-release.yml, .github/workflows/build-npm.yml, CHANGELOG.md, PULL_REQUEST_TEMPLATE.md, package.json
Add PULL_REQUEST_TEMPLATE.md file to the repository.
Update Node.js to v18 in GitHub Actions.
https://issues.folio.org/browse/UITAG-68
https://issues.folio.org/browse/UITAG-72
=> UITAG-68, UITAG-72 - Add Pull Request Template md file, Update Node.js to v18 in GitHub Actions

CHANGELOG.md, package.json
Poppy release v8.0.2
While it's helpful for reviewers to help identify potential problems, …
=> Release v8.0.2

CHANGELOG.md, package.json
https://folio-org.atlassian.net/browse/UITAG-76
While it's helpful for reviewers to help …
=> Release v8.1.0 - Quesnelia Release

.github/workflows/build-npm-release.yml, .github/workflows/build-npm.yml, CHANGELOG.md
[UITAG-78](https://folio-org.atlassian.net/browse/UITAG-78) 
While it's helpful for …
=> UITAG-78 - upgrade 'actions/upload-artifact' version to v4

CHANGELOG.md, package.json
Release v8.2.1
While it's helpful for reviewers to help identify potential problems, …
=> Release v8.2.1

CHANGELOG.md, package.json
update changelog.md and package.json details after releasing v8.2.1
While it's helpful for …
=> update changelog.md and package.json details after releasing v8.2.1
